/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as SummaryMeetingIdRouteImport } from './routes/summary.$meetingId'
import { Route as MeetMeetingIdRouteImport } from './routes/meet.$meetingId'
import { Route as JoinOrgIdRouteImport } from './routes/join.$orgId'
import { Route as DashboardUpgradeRouteImport } from './routes/dashboard.upgrade'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardScheduleRouteImport } from './routes/dashboard.schedule'
import { Route as DashboardRecordingsRouteImport } from './routes/dashboard.recordings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPartnersRouteImport } from './routes/dashboard.partners'
import { Route as DashboardMeetingsRouteImport } from './routes/dashboard.meetings'
import { Route as DashboardFaqRouteImport } from './routes/dashboard.faq'
import { Route as DashboardEnterpriseRouteImport } from './routes/dashboard.enterprise'
import { Route as DashboardDeveloperRouteImport } from './routes/dashboard.developer'
import { Route as DashboardContactsRouteImport } from './routes/dashboard.contacts'
import { Route as DashboardClassroomRouteImport } from './routes/dashboard.classroom'
import { Route as DashboardAcademyRouteImport } from './routes/dashboard.academy'
import { Route as DashboardAboutRouteImport } from './routes/dashboard.about'
import { Route as DashboardClassroomClassIdRouteImport } from './routes/dashboard.classroom.$classId'

const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SummaryMeetingIdRoute = SummaryMeetingIdRouteImport.update({
  id: '/summary/$meetingId',
  path: '/summary/$meetingId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetMeetingIdRoute = MeetMeetingIdRouteImport.update({
  id: '/meet/$meetingId',
  path: '/meet/$meetingId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinOrgIdRoute = JoinOrgIdRouteImport.update({
  id: '/join/$orgId',
  path: '/join/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUpgradeRoute = DashboardUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScheduleRoute = DashboardScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecordingsRoute = DashboardRecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPartnersRoute = DashboardPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMeetingsRoute = DashboardMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFaqRoute = DashboardFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnterpriseRoute = DashboardEnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeveloperRoute = DashboardDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContactsRoute = DashboardContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClassroomRoute = DashboardClassroomRouteImport.update({
  id: '/classroom',
  path: '/classroom',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAcademyRoute = DashboardAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAboutRoute = DashboardAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClassroomClassIdRoute =
  DashboardClassroomClassIdRouteImport.update({
    id: '/$classId',
    path: '/$classId',
    getParentRoute: () => DashboardClassroomRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/enterprise': typeof EnterpriseRoute
  '/faq': typeof FaqRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/academy': typeof DashboardAcademyRoute
  '/dashboard/classroom': typeof DashboardClassroomRouteWithChildren
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/developer': typeof DashboardDeveloperRoute
  '/dashboard/enterprise': typeof DashboardEnterpriseRoute
  '/dashboard/faq': typeof DashboardFaqRoute
  '/dashboard/meetings': typeof DashboardMeetingsRoute
  '/dashboard/partners': typeof DashboardPartnersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/recordings': typeof DashboardRecordingsRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upgrade': typeof DashboardUpgradeRoute
  '/join/$orgId': typeof JoinOrgIdRoute
  '/meet/$meetingId': typeof MeetMeetingIdRoute
  '/summary/$meetingId': typeof SummaryMeetingIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/classroom/$classId': typeof DashboardClassroomClassIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/auth': typeof AuthRoute
  '/enterprise': typeof EnterpriseRoute
  '/faq': typeof FaqRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/academy': typeof DashboardAcademyRoute
  '/dashboard/classroom': typeof DashboardClassroomRouteWithChildren
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/developer': typeof DashboardDeveloperRoute
  '/dashboard/enterprise': typeof DashboardEnterpriseRoute
  '/dashboard/faq': typeof DashboardFaqRoute
  '/dashboard/meetings': typeof DashboardMeetingsRoute
  '/dashboard/partners': typeof DashboardPartnersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/recordings': typeof DashboardRecordingsRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upgrade': typeof DashboardUpgradeRoute
  '/join/$orgId': typeof JoinOrgIdRoute
  '/meet/$meetingId': typeof MeetMeetingIdRoute
  '/summary/$meetingId': typeof SummaryMeetingIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/classroom/$classId': typeof DashboardClassroomClassIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/enterprise': typeof EnterpriseRoute
  '/faq': typeof FaqRoute
  '/onboarding': typeof OnboardingRoute
  '/partners': typeof PartnersRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/academy': typeof DashboardAcademyRoute
  '/dashboard/classroom': typeof DashboardClassroomRouteWithChildren
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/developer': typeof DashboardDeveloperRoute
  '/dashboard/enterprise': typeof DashboardEnterpriseRoute
  '/dashboard/faq': typeof DashboardFaqRoute
  '/dashboard/meetings': typeof DashboardMeetingsRoute
  '/dashboard/partners': typeof DashboardPartnersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/recordings': typeof DashboardRecordingsRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upgrade': typeof DashboardUpgradeRoute
  '/join/$orgId': typeof JoinOrgIdRoute
  '/meet/$meetingId': typeof MeetMeetingIdRoute
  '/summary/$meetingId': typeof SummaryMeetingIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/classroom/$classId': typeof DashboardClassroomClassIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/auth'
    | '/dashboard'
    | '/enterprise'
    | '/faq'
    | '/onboarding'
    | '/partners'
    | '/profile'
    | '/terms'
    | '/use-cases'
    | '/dashboard/about'
    | '/dashboard/academy'
    | '/dashboard/classroom'
    | '/dashboard/contacts'
    | '/dashboard/developer'
    | '/dashboard/enterprise'
    | '/dashboard/faq'
    | '/dashboard/meetings'
    | '/dashboard/partners'
    | '/dashboard/profile'
    | '/dashboard/recordings'
    | '/dashboard/schedule'
    | '/dashboard/settings'
    | '/dashboard/upgrade'
    | '/join/$orgId'
    | '/meet/$meetingId'
    | '/summary/$meetingId'
    | '/dashboard/'
    | '/dashboard/classroom/$classId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/auth'
    | '/enterprise'
    | '/faq'
    | '/onboarding'
    | '/partners'
    | '/profile'
    | '/terms'
    | '/use-cases'
    | '/dashboard/about'
    | '/dashboard/academy'
    | '/dashboard/classroom'
    | '/dashboard/contacts'
    | '/dashboard/developer'
    | '/dashboard/enterprise'
    | '/dashboard/faq'
    | '/dashboard/meetings'
    | '/dashboard/partners'
    | '/dashboard/profile'
    | '/dashboard/recordings'
    | '/dashboard/schedule'
    | '/dashboard/settings'
    | '/dashboard/upgrade'
    | '/join/$orgId'
    | '/meet/$meetingId'
    | '/summary/$meetingId'
    | '/dashboard'
    | '/dashboard/classroom/$classId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/auth'
    | '/dashboard'
    | '/enterprise'
    | '/faq'
    | '/onboarding'
    | '/partners'
    | '/profile'
    | '/terms'
    | '/use-cases'
    | '/dashboard/about'
    | '/dashboard/academy'
    | '/dashboard/classroom'
    | '/dashboard/contacts'
    | '/dashboard/developer'
    | '/dashboard/enterprise'
    | '/dashboard/faq'
    | '/dashboard/meetings'
    | '/dashboard/partners'
    | '/dashboard/profile'
    | '/dashboard/recordings'
    | '/dashboard/schedule'
    | '/dashboard/settings'
    | '/dashboard/upgrade'
    | '/join/$orgId'
    | '/meet/$meetingId'
    | '/summary/$meetingId'
    | '/dashboard/'
    | '/dashboard/classroom/$classId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EnterpriseRoute: typeof EnterpriseRoute
  FaqRoute: typeof FaqRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnersRoute: typeof PartnersRoute
  ProfileRoute: typeof ProfileRoute
  TermsRoute: typeof TermsRoute
  UseCasesRoute: typeof UseCasesRoute
  JoinOrgIdRoute: typeof JoinOrgIdRoute
  MeetMeetingIdRoute: typeof MeetMeetingIdRoute
  SummaryMeetingIdRoute: typeof SummaryMeetingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/summary/$meetingId': {
      id: '/summary/$meetingId'
      path: '/summary/$meetingId'
      fullPath: '/summary/$meetingId'
      preLoaderRoute: typeof SummaryMeetingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet/$meetingId': {
      id: '/meet/$meetingId'
      path: '/meet/$meetingId'
      fullPath: '/meet/$meetingId'
      preLoaderRoute: typeof MeetMeetingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$orgId': {
      id: '/join/$orgId'
      path: '/join/$orgId'
      fullPath: '/join/$orgId'
      preLoaderRoute: typeof JoinOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/upgrade': {
      id: '/dashboard/upgrade'
      path: '/upgrade'
      fullPath: '/dashboard/upgrade'
      preLoaderRoute: typeof DashboardUpgradeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schedule': {
      id: '/dashboard/schedule'
      path: '/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof DashboardScheduleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recordings': {
      id: '/dashboard/recordings'
      path: '/recordings'
      fullPath: '/dashboard/recordings'
      preLoaderRoute: typeof DashboardRecordingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/partners': {
      id: '/dashboard/partners'
      path: '/partners'
      fullPath: '/dashboard/partners'
      preLoaderRoute: typeof DashboardPartnersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/meetings': {
      id: '/dashboard/meetings'
      path: '/meetings'
      fullPath: '/dashboard/meetings'
      preLoaderRoute: typeof DashboardMeetingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/faq': {
      id: '/dashboard/faq'
      path: '/faq'
      fullPath: '/dashboard/faq'
      preLoaderRoute: typeof DashboardFaqRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/enterprise': {
      id: '/dashboard/enterprise'
      path: '/enterprise'
      fullPath: '/dashboard/enterprise'
      preLoaderRoute: typeof DashboardEnterpriseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/developer': {
      id: '/dashboard/developer'
      path: '/developer'
      fullPath: '/dashboard/developer'
      preLoaderRoute: typeof DashboardDeveloperRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contacts': {
      id: '/dashboard/contacts'
      path: '/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof DashboardContactsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/classroom': {
      id: '/dashboard/classroom'
      path: '/classroom'
      fullPath: '/dashboard/classroom'
      preLoaderRoute: typeof DashboardClassroomRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/academy': {
      id: '/dashboard/academy'
      path: '/academy'
      fullPath: '/dashboard/academy'
      preLoaderRoute: typeof DashboardAcademyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/about': {
      id: '/dashboard/about'
      path: '/about'
      fullPath: '/dashboard/about'
      preLoaderRoute: typeof DashboardAboutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/classroom/$classId': {
      id: '/dashboard/classroom/$classId'
      path: '/$classId'
      fullPath: '/dashboard/classroom/$classId'
      preLoaderRoute: typeof DashboardClassroomClassIdRouteImport
      parentRoute: typeof DashboardClassroomRoute
    }
  }
}

interface DashboardClassroomRouteChildren {
  DashboardClassroomClassIdRoute: typeof DashboardClassroomClassIdRoute
}

const DashboardClassroomRouteChildren: DashboardClassroomRouteChildren = {
  DashboardClassroomClassIdRoute: DashboardClassroomClassIdRoute,
}

const DashboardClassroomRouteWithChildren =
  DashboardClassroomRoute._addFileChildren(DashboardClassroomRouteChildren)

interface DashboardRouteChildren {
  DashboardAboutRoute: typeof DashboardAboutRoute
  DashboardAcademyRoute: typeof DashboardAcademyRoute
  DashboardClassroomRoute: typeof DashboardClassroomRouteWithChildren
  DashboardContactsRoute: typeof DashboardContactsRoute
  DashboardDeveloperRoute: typeof DashboardDeveloperRoute
  DashboardEnterpriseRoute: typeof DashboardEnterpriseRoute
  DashboardFaqRoute: typeof DashboardFaqRoute
  DashboardMeetingsRoute: typeof DashboardMeetingsRoute
  DashboardPartnersRoute: typeof DashboardPartnersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRecordingsRoute: typeof DashboardRecordingsRoute
  DashboardScheduleRoute: typeof DashboardScheduleRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUpgradeRoute: typeof DashboardUpgradeRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAboutRoute: DashboardAboutRoute,
  DashboardAcademyRoute: DashboardAcademyRoute,
  DashboardClassroomRoute: DashboardClassroomRouteWithChildren,
  DashboardContactsRoute: DashboardContactsRoute,
  DashboardDeveloperRoute: DashboardDeveloperRoute,
  DashboardEnterpriseRoute: DashboardEnterpriseRoute,
  DashboardFaqRoute: DashboardFaqRoute,
  DashboardMeetingsRoute: DashboardMeetingsRoute,
  DashboardPartnersRoute: DashboardPartnersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRecordingsRoute: DashboardRecordingsRoute,
  DashboardScheduleRoute: DashboardScheduleRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUpgradeRoute: DashboardUpgradeRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EnterpriseRoute: EnterpriseRoute,
  FaqRoute: FaqRoute,
  OnboardingRoute: OnboardingRoute,
  PartnersRoute: PartnersRoute,
  ProfileRoute: ProfileRoute,
  TermsRoute: TermsRoute,
  UseCasesRoute: UseCasesRoute,
  JoinOrgIdRoute: JoinOrgIdRoute,
  MeetMeetingIdRoute: MeetMeetingIdRoute,
  SummaryMeetingIdRoute: SummaryMeetingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
